// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';

export function AdvanceDemoRun():Promise<orchestrator.DashboardState>;

export function CreateRun(arg1:orchestrator.RunCreationInput):Promise<orchestrator.DashboardState>;

export function DeleteAIProvider(arg1:string):Promise<orchestrator.DashboardState>;

export function GetDashboardState():Promise<orchestrator.DashboardState>;

export function ProbeAIProvider(arg1:orchestrator.AIProviderInput):Promise<string>;

export function ResetDemoRun():Promise<orchestrator.DashboardState>;

export function UpdateRuntimeSettings(arg1:orchestrator.SettingsInput):Promise<orchestrator.DashboardState>;

export function UpsertAIProvider(arg1:orchestrator.AIProviderInput):Promise<orchestrator.DashboardState>;
