// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceDemoRun() {
  return window['go']['main']['App']['AdvanceDemoRun']();
}

export function CreateRun(arg1) {
  return window['go']['main']['App']['CreateRun'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['main']['App']['DeleteAIProvider'](arg1);
}

export function GetDashboardState() {
  return window['go']['main']['App']['GetDashboardState']();
}

export function ProbeAIProvider(arg1) {
  return window['go']['main']['App']['ProbeAIProvider'](arg1);
}

export function ResetDemoRun() {
  return window['go']['main']['App']['ResetDemoRun']();
}

export function UpdateRuntimeSettings(arg1) {
  return window['go']['main']['App']['UpdateRuntimeSettings'](arg1);
}

export function UpsertAIProvider(arg1) {
  return window['go']['main']['App']['UpsertAIProvider'](arg1);
}
